name: Publish Docker
on: 
  push: 
    branches:
      - dev
jobs:
  latest-and-amd64:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@master
      - name: DockerHub login
        env: 
          DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
          DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
        run: |
          echo "${DOCKER_PASSWORD}" | docker login --username ${DOCKER_USERNAME} --password-stdin
      - name: Set up docker buildx
        id: buildx
        uses: crazy-max/ghaction-docker-buildx@v1
        with:
          version: latest
      - name: Build Dockerfile and push to DockerHub
        run: |
          REPO_NAME=${{ secrets.DOCKER_REPOSITORY }}
          docker buildx build \
            --platform linux/amd64 \
            -t ${REPO_NAME}:unstable -t ${REPO_NAME}:unstable-${GITHUB_SHA} \
            --push \
            . -f Dockerfile